config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  resources :surveys, except: [:index, :show, :edit, :new, :update, :destroy]
  resources :managers, except: [:index, :show, :edit, :update, :destroy]
  resources :teams, except: [:index, :show]
  resources :responses, except: [:index, :show, :edit, :new, :update, :destroy]
  resources :ticket_responses, except: [:index, :show, :edit, :new, :update, :destroy]
  resources :users, except: [:new, :index, :show, :edit, :update, :destroy]  
  resources :tickets, except: [:new, :show, :index, :edit, :update, :destroy]
    
  get '/signup', to: 'users#new'
  get '/login',  to: 'sessions#new'    
  post '/login',  to: 'sessions#create'    
  get '/logout', to: 'sessions#destroy' 
  
  get '/about', to: 'static_pages#about'
    
  get 'dashboard', to: 'users#dashboard', as: 'user_dashboard'
  get 'dashboard/teams/:id', to: 'users#team_list', as: 'user_team_list'    
  get 'dashboard/teams/:id/weekly_surveys/:from', to: 'users#weekly_surveys', as: 'weekly_surveys'
    
  get 'manager_dashboard', to: 'managers#dashboard', as: 'manager_dashboard'
  get 'team_health/:id/metrics', to: 'managers#team_health', as: 'team_health'
    
  get 'teams/:id/members', to: 'teams#edit_members', as: 'edit_members'
  post 'teams/:id/members/add', to: 'teams#add_member', as: 'confirm_add_member'
  post 'teams/:id/members/remove', to: 'teams#remove_member', as: 'confirm_remove_member'
  
  get 'teams/:id/tickets', to: 'managers#tickets', as: 'team_tickets'
  get 'team_health/:id/metrics/:date/details', to: 'managers#health_details', as: 'team_health_details'
    
    # route to get the team associated with the ticket
  get 'teams/:id/tickets/new', to: 'tickets#new', as: 'new_team_ticket'
  post 'teams/:id/tickets', to: 'tickets#create', as: 'create_team_ticket'
    
  #For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  match "*path", to: "users#dashboard", via: :all
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
      get_dashboard
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>About our Application!</h1>
<center>
<p style="margin-left:10px; margin-right:5%;width:50vw;">
    <br>    
    Welcome to PAEN, a team health monitoring web application developed by 6 Management Engineering Undergraduate Students from the University of Waterloo. 
    This application was developed for Dr. Smucker's Winter 2021 MSCI 342 - Software Engineering class.
    <br> <br>
    Our application is named <b>PAEN</b> and its an acronym for <b>P</b>rofessional <b>A</b>ccessible <b>E</b>valuation <b>N</b>ow. 
    We aim to give a professionally focused solution, that is accessible to all users. 
    The goal of the program is to evaluate, and our site has 100% uptime and is available at all times.
    <br> <br>
    Our logo is a modern take on our application name and also contains our motto "A healthier team starts here".
    The primary focus of our application is to monitor team health and identify issues and weaknesses within teams.
    Our motto and logo embody our mission of ensuring all teams that use our application have their issues identified and solutions are being worked towards.
    
    <br> <br>
    <br> <br>
    <br> <br>
    
    <div class="link-container"><%= link_to 'Return to Dashboard', user_dashboard_path %></div>
        
</p>
</center>

app/views/static_pages/home.html.erb
<h1>Login</h1>

<% if logged_in? %>
  <p><%= link_to 'List All Users', users_path %></p>
  <p><%= link_to 'Logout', logout_path %></p>
<% else %>
  <p><%= link_to 'Login', login_path %></p>
  <p><%= link_to 'Create an Account', signup_path %></p>
<% end %>