config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  resources :surveys, except: [:index, :show, :edit, :new, :update, :destroy]
  resources :managers, except: [:index, :show, :edit, :update, :destroy]
  resources :teams, except: [:index, :show]
  resources :responses, except: [:index, :show, :edit, :new, :update, :destroy]
  resources :ticket_responses, except: [:index, :show, :edit, :new, :update, :destroy]
  resources :users, except: [:new, :index, :show, :edit, :update, :destroy]  
  resources :tickets, except: [:new, :show, :index, :edit, :update, :destroy]
    
  get '/signup', to: 'users#new'
  get '/login',  to: 'sessions#new'    
  post '/login',  to: 'sessions#create'    
  get '/logout', to: 'sessions#destroy' 
  
  get '/about', to: 'static_pages#about'
    
  get 'dashboard', to: 'users#dashboard', as: 'user_dashboard'
  get 'dashboard/teams/:id', to: 'users#team_list', as: 'user_team_list'    
  get 'dashboard/teams/:id/weekly_surveys/:from', to: 'users#weekly_surveys', as: 'weekly_surveys'
    
  get 'manager_dashboard', to: 'managers#dashboard', as: 'manager_dashboard'
  get 'team_health/:id/metrics', to: 'managers#team_health', as: 'team_health'
    
  get 'teams/:id/members', to: 'teams#edit_members', as: 'edit_members'
  post 'teams/:id/members/add', to: 'teams#add_member', as: 'confirm_add_member'
  post 'teams/:id/members/remove', to: 'teams#remove_member', as: 'confirm_remove_member'
  
  get 'teams/:id/tickets', to: 'managers#tickets', as: 'team_tickets'
  get 'team_health/:id/metrics/:date/details', to: 'managers#health_details', as: 'team_health_details'
    
    # route to get the team associated with the ticket
  get 'teams/:id/tickets/new', to: 'tickets#new', as: 'new_team_ticket'
  post 'teams/:id/tickets', to: 'tickets#create', as: 'create_team_ticket'
    
  #For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  match "*path", to: "users#dashboard", via: :all
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :flag
    
    has_and_belongs_to_many :teams
    has_many :surveys
    has_and_belongs_to_many :tickets
    has_secure_password
  
    validates :first_name, presence: true, allow_blank: false
    validates :last_name, presence: true, allow_blank: false
    validates :watiam, format: {without: /[\s\W]/}, presence: true, allow_blank: false
    validates :password, length: {in: 6..25}, on: :create, format: {without: /\s/}, allow_blank: false, presence: true

    def full_name_with_watiam
        "#{first_name} #{last_name} (Watiam: #{watiam} )"
    end 
    
    def self.get_ordered_survey_indicator(team, current_weekly_survey_due_date)
      ordered_users = []
      team.users.each { |user|
        survey = Survey.find_by(user_id: user.id, team_id: team.id, date: current_weekly_survey_due_date)
        if survey && survey.responses.exists?
          ordered_users << [user, "Yes"]
        else
          ordered_users.insert(0, [user, "No"]) 
        end
      }
      return ordered_users
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorized_to_modify_and_destroy, only: [:edit, :update, :destroy]
  before_action :check_path, except: [:new, :create]
    
  # GET /users/new
  def new
    user_params = params
    @user = User.new
    if user_params[:flag] == "User"
      @user = User.create
    end
  end
    
  # GET /dashboard
  def dashboard
     if current_user_is_manager
         redirect_to manager_dashboard_path
     else
         @CURRENT_SURVEY_DUE_DATE = CURRENT_SURVEY_DUE_DATE
         @user = current_user #get logged in user from session
         @teams = @user.teams
         @survey_completed = {}
         @ticket_completed = {}
         @teams.each do |team| #for each team user is on, check if user completed the survey for that team    
             @survey = Survey.find_by(user_id: current_user.id, team_id: team.id, date: CURRENT_SURVEY_DUE_DATE)
             if !@survey
               @survey = Survey.create(user_id: current_user.id, team_id: team.id, date: CURRENT_SURVEY_DUE_DATE)
               @survey_completed[team] = false
             else
               if @survey and @survey.responses.exists? 
                 @survey_completed[team] = true
               else 
                 @survey_completed[team] = false
               end
             end
             @users_completed_ticket = team.get_users_with_tickets(current_user, CURRENT_SURVEY_DUE_DATE)
             @total_users_on_team = team.users.length
             @users_completed_ticket.length == @total_users_on_team ? @ticket_completed[team] = true : @ticket_completed[team] = false             
         end
         
         @teamHealth = {}
         @teams.each do |team|
             @teamHealth[team] = team.weekly_survey_team_health(0, CURRENT_SURVEY_DUE_DATE)
         end
         
     end
  end
    
  # GET /dashboard/teams/1 
  def team_list
     @team = Team.find(params[:id])
     if current_user_is_manager
         redirect_to team_health_path(@team)
     else
          if !current_user_is_on_team(@team)
              redirect_to user_dashboard_path, alert: 'You do not have permission to view this team.'
          else
              @health_value = @team.get_total_team_health(0, CURRENT_SURVEY_DUE_DATE) 
          end
          @users = @team.users
          @manager = @team.managers.first  #for now only one manager per team
      end
  end
    
  # GET /weekly_surveys/teams/1
  def weekly_surveys
    @from = params[:from]
    @team = Team.find(params[:id])
    if current_user_is_manager
         redirect_to manager_dashboard_path, alert: 'You do not have permission to respond to surveys.'
    elsif !current_user_is_on_team(@team)
         redirect_to user_dashboard_path, alert: 'You do not have permission to respond to another team\'s survey.'
    end
    @survey = Survey.find_by(user: current_user.id, team: @team.id, date: CURRENT_SURVEY_DUE_DATE)
    if @survey && @survey.responses.exists?
      redirect_to user_dashboard_path, notice: "You have already submitted this week's survey."
    end
    q1 = "How do you feel about this week in comparison to last week?"
    q2 = "How did you feel about this week?"
    q3 = "How would you rate your communication with your team members this week?"
    q4 = "How do you feel about the workload you had this week?"
    @questions = [q1,q2,q3,q4]
  end
  
  # POST /users
  def create
    if user_params[:flag] == "User"
      @user = User.new(user_params)
    else
      @user = Manager.new(user_params)
    end
      
    @userCannotBeCreated = false
    @watiamList = User.select("watiam") + Manager.select("watiam")
    @watiamList.each do |x|
        if @user.watiam == x.watiam
            @userCannotBeCreated = true
        end
    end
    if @userCannotBeCreated == false
        if @user.save
          log_in @user
          redirect_to root_url, notice: 'Account created and logged in.'
        else
          render :new
        end
    else
        flash[:alert] = "That WATIAM has an account associated with it already."
        render :new
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    
    def check_path
        current_path = request.env['PATH_INFO']
        if current_path == "/users" || current_path == "/managers"
            redirect_to user_dashboard_path
        end
    end
    
    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :flag, :watiam, :password, :first_name, :last_name, :password_confirmation)
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 

<div class="row-container">   
  <%= form.radio_button :flag, "User", :checked => true, :style => "display: none;" %>
  <%= form.label :flag_user, "User", :class => 'label' %> 
  <%= form.radio_button :flag, "Manager" %>
  <%= form.label :flag_manager, "Manager", :class => 'label' %>     
</div> 
<!-- 
  - Source (https://stackoverflow.com/questions/50453091/override-a-default-value-in-a-rails-form) used for understanding how to set input values if default values not provided
-->

<div class="field">
    <%= form.text_field :watiam, value: (form.object.watiam || params[:watiam]), placeholder: "Watiam" %>
  </div>
<div class="field">
    <%= form.text_field :first_name, value: (form.object.first_name || params[:first_name]), placeholder: "First Name" %>
  </div>
<div class="field">
    <%= form.text_field :last_name, value: (form.object.last_name || params[:last_name]), placeholder: "Last Name" %>
  </div>

 <div class="field">
    <%= form.password_field :password, value: (form.object.password || params[:password]), placeholder: "Password" %>
  </div>

  <div class="field">
    <%= form.password_field :password_confirmation, value: (form.object.password_confirmation || params[:password_confirmation]), placeholder: "Password Confirmation" %>
  </div>

<div class="actions">
    <%= form.submit "Create Account", style: 'width: 180px' %>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<h1>Welcome <%= @user.first_name.capitalize %>!</h1>
<h3>Weekly Survey Due Date: <%= @CURRENT_SURVEY_DUE_DATE-1 %> 11:59PM UTC</h3>
<br>
<% if @teams.empty? %>

<h2> You're not a part of a team yet! Let your instructor know to add you to a team. </h2>

<% else %>

<table class="users_table">
  <thead>
    <tr>
      <th>My Teams</th>
      <th>Weekly Survey</th>
      <th>Current Weekly Health</th>
      <th>Ticket</th>
    </tr>
  </thead>

  <tbody>
    <% @teams.each do |team| %>
      <tr>
        <td><%= link_to team.name, user_team_list_path(id: team.id) %></td>
        <td><% if @survey_completed[team] %>
                 Complete
            <% else %>
                 <%= link_to "Incomplete", weekly_surveys_path(id: team.id, from: "dashboard") %>
            <% end %>
        </td>
        <% if team.get_total_team_health(0, @CURRENT_SURVEY_DUE_DATE).to_i < 30 %>
            <td class="red_notice"><%= team.get_total_team_health(0, @CURRENT_SURVEY_DUE_DATE) %>%</td>
        <% elsif team.get_total_team_health(0, @CURRENT_SURVEY_DUE_DATE).to_i > 90 %>
            <td class="green_notice"><%= team.get_total_team_health(0, @CURRENT_SURVEY_DUE_DATE) %>%</td>
        <% else %>
            <td><%= team.get_total_team_health(0, @CURRENT_SURVEY_DUE_DATE) %>%</td>
        <% end %>
        <td><% if team.users.length > 1 %>
                <% if @ticket_completed[team] %>
                    Complete
                <% else %>
                    <%= link_to "Create Ticket", new_team_ticket_path(id: team.id, from: "dashboard") %>
                <% end %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<br><br>
<div class="link-container">
    <a href="#help"><h2>Confused?🤔 Get information here!</h2></a>
</div>

<div id="help" class="overlay">
  <div class="popup">
    <h3 style="text-align:left">Teams:</h3>
    <p style="margin-left:10px; margin-right:5%;">
        Teams are where you can view all of the teams you are on!
        <br>
        <br>
        The displayed table shows you all of your teams, their weekly health, the status of the survey completions, and a link to create a ticket for that team.
        <br>
        By the way, you can find out more about who is on your team by clicking on the team name.
        <br><br>
        <b>What if I'm not on any teams yet?😲</b>
        <br>
        No problem! Hopefully your manager will add you to a team. If you aren't on a team yet, and you are not expecting to be on a team, then you have nothing to worry about
    </p>
    <h3 style="text-align:left">Weekly Survey Information:</h3>
    <p style="margin-left:10px; margin-right:5%;">
        The weekly survey information is where you will be reflecting about your past week!🙌🙌🙌
        <br><br>
        <b>How does this work?</b>
        <br>
        Every week, you will be able to respond to questions with an number between 1-5.
        <br>
        Additionally, you can give peer feedback to your teammate(s) by creating a ticket which will be reflected to your manager and the team health.
        <br><br>
        <b>What do these ratings mean?</b>
        <br>
        Generally, we like to think these ratings as follows:
        <br>
    </p>
    <p style="margin-left:30px">
        1: 😭 - Absolutely terrible
        <br>
        2: 😟 - It could be better
        <br>
        3: 😐 - Meh, could be better could be worse.
        <br>
        4: 🙂 - Hey, this is pretty good
        <br>
        5: 🥳 - Loved it; 10/10 would do that again
    </p>
    <br>
    <p style="margin-left:10px; margin-right:5%;">
        <b>What is the Weekly Survey Due Date?</b>
        <br>
        The weekly survey due date is, well, the deadline for you to submit that week's survey.
        <br>
        Every week you will be able to complete a new survey for that week.
        <br>
        The due date is displayed in UTC to accomodate for the fact that team members may be in different timezones. 
        <br><br>
        <b>Cool! But what is the point of the surveys?</b>
        <br>
        We are so happy you asked!
        <br>
        We make sure to record all of the ratings your teammates input every week. This data is then processed by a super secret algorithm our programming wizards created!🧙 After the algorithm has chewed on the ratings, it spits out a value representing your team's health!
        <br><br>
        <b>Yeah and?</b>
        <br>
        Now this is the cool part! Your team health is an overall reflection of your individual team member's feelings about work as well as highlight any inter-personal team issues within your team. The best part? You get to see all of this from one website!
        <br><br>
    </p>
    <a href="#">Close</a>
  </div>
</div>

app/views/users/new.html.erb
<h1>Create Account</h1>

<%= render 'form', user: @user %>

<div class="link-container">   
    <%= link_to 'Already have an account? Sign in here!', login_path %>
</div>

app/views/users/team_list.html.erb
<h1><%=@team.name%> Details</h1>

<%= render template: 'teams/health' %>

<h2>Members</h2>
<%= render template: 'teams/members' %>

<br><br>
<div class="user_team_links">
    <br>
    <div class="link-container"><%= link_to 'Weekly Surveys', weekly_surveys_path(id: @team.id, from: "team") %> | 
        <%= link_to 'Create A Ticket', new_team_ticket_path(id: @team.id, from: "team") %></div>
    
    
    <div class="link-container"><%= link_to 'Return to Dashboard', user_dashboard_path %></div>
</div>
<br><br>


<div class="link-container"><a href="#help"><h2>Confused?🤔 Get information here!</h2></a></div>

<div id="help" class="overlay">
  <div class="popup">
    <h3 style="text-align:left">Team Health:</h3>
    <p style="margin-left:10px; margin-right:5%;">
        This is the place to be if you want to know more about your team's health!
    </p>
    <h3 style="text-align:left">Current Week's Team Health:</h3>
    <p style="margin-left:10px; margin-right:5%;">
        At the top of the page you will find a quick visualization that reflects your current week's team health.
        <br><br>
        The weekly team health is a direct reflection of how your team feels about the current week as well your their teammates!
        <br>
        It's simple! The higher the number, the happier your team is!🥳
        <br><br>
        Here at Paen, we recommend that you do your best to motivate you to always complete your surveys, as the more team members complete their surveys, the more accurate our estimation will be!
    </p>
    <h3 style="text-align:left">What if I don't complete my weekly survey?</h3>
    <p style="margin-left:10px; margin-right:5%;">
        Nothing. From our point-of-view that is just one less data point for us to use. 😭 However, your manager likely really wants you to complete your weekly surveys. By completing your weekly surveys you may directly impact how your team is run and the decisions made by your manager.
        <br><br>
        After all, teamwork makes the dream work, right?🧐
    </p>
    <a href="#">Close</a>
  </div>
</div>

app/views/users/weekly_surveys.html.erb
<h1>WEEKLY SURVEYS</h1>
<div class = "due-date">
    <h3>Weekly Survey Due Date: <%= @survey.date-1 %> 11:59PM UTC</h3>
</div>
<! -- Using code from my (emma) spellmanager assignment -->
<! -- also using https://guides.rubyonrails.org/form_helpers.html#making-select-boxes-with-ease -->

<%= form_with url: "/responses", method: :post do |form| %>
    <% for i in 0..@questions.length-1 %> 
        <div class="subtitle"> <%= "#{i+1}. #{@questions[i]}" %> </div>
        <div class="option-container">
            <%= form.radio_button :"answer#{i+1}", 1, :pattern => '^[1-5]{1}?$'%>
            <%= form.label :"answer#{i+1}_1", "1", :class => 'label' %>
            <%= form.radio_button :"answer#{i+1}", 2, :pattern => '^[1-5]{1}?$' %>
            <%= form.label :"answer#{i+1}_2", "2", :class => 'label' %>
            <%= form.radio_button :"answer#{i+1}", 3, :pattern => '^[1-5]{1}?$' %>
            <%= form.label :"answer#{i+1}_3", "3", :class => 'label' %>
            <%= form.radio_button :"answer#{i+1}", 4, :pattern => '^[1-5]{1}?$' %>
            <%= form.label :"answer#{i+1}_4", "4", :class => 'label' %>
            <%= form.radio_button :"answer#{i+1}", 5, :pattern => '^[1-5]{1}?$' %>
            <%= form.label :"answer#{i+1}_5", "5", :class => 'label' %>
        </div>             
    <% end %>

    <%= form.hidden_field :survey_id, value: @survey.id %>
    <%= form.hidden_field :num_of_questions, value: @questions.count %>
    <h5><%= form.submit %></h5>
<% end %>
<div class="user_team_links">
    <% if @from == "dashboard" %>
        <div class="link-container"><%= link_to "Back to Dashboard", user_dashboard_path %></div>
    <% elsif @from == "team" %>
        <div class="link-container"><%= link_to "Back to #{@team.name}", user_team_list_path(@team.id) %></div> 
    <% end %>
</div>

<br><br>
<div class="link-container"><a href="#help"><h2>Confused?🤔 Get information here!</h2></a></div>

<div id="help" class="overlay">
  <div class="popup">
    <h3 style="text-align:left">Weekly Surveys:</h3>
    <p style="margin-left:10px; margin-right:5%;">
        Time to get in touch with your emotions and feelings about the week!
        <br>
        <br>
        For each question, try to think about the ratings in the following context:
        <br>
    </p>
    <p style="margin-left:30px">
        1: 😭 - Absolutely terrible
        <br>
        2: 😟 - It could be better
        <br>
        3: 😐 - Meh, could be better could be worse.
        <br>
        4: 🙂 - Hey, this is pretty good
        <br>
        5: 🥳 - Loved it; 10/10 would do that again
    </p>
    <a href="#">Close</a>
  </div>
</div>