config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  resources :surveys, except: [:index, :show, :edit, :new, :update, :destroy]
  resources :managers, except: [:index, :show, :edit, :update, :destroy]
  resources :teams, except: [:index, :show]
  resources :responses, except: [:index, :show, :edit, :new, :update, :destroy]
  resources :ticket_responses, except: [:index, :show, :edit, :new, :update, :destroy]
  resources :users, except: [:new, :index, :show, :edit, :update, :destroy]  
  resources :tickets, except: [:new, :show, :index, :edit, :update, :destroy]
    
  get '/signup', to: 'users#new'
  get '/login',  to: 'sessions#new'    
  post '/login',  to: 'sessions#create'    
  get '/logout', to: 'sessions#destroy' 
  
  get '/about', to: 'static_pages#about'
    
  get 'dashboard', to: 'users#dashboard', as: 'user_dashboard'
  get 'dashboard/teams/:id', to: 'users#team_list', as: 'user_team_list'    
  get 'dashboard/teams/:id/weekly_surveys/:from', to: 'users#weekly_surveys', as: 'weekly_surveys'
    
  get 'manager_dashboard', to: 'managers#dashboard', as: 'manager_dashboard'
  get 'team_health/:id/metrics', to: 'managers#team_health', as: 'team_health'
    
  get 'teams/:id/members', to: 'teams#edit_members', as: 'edit_members'
  post 'teams/:id/members/add', to: 'teams#add_member', as: 'confirm_add_member'
  post 'teams/:id/members/remove', to: 'teams#remove_member', as: 'confirm_remove_member'
  
  get 'teams/:id/tickets', to: 'managers#tickets', as: 'team_tickets'
  get 'team_health/:id/metrics/:date/details', to: 'managers#health_details', as: 'team_health_details'
    
    # route to get the team associated with the ticket
  get 'teams/:id/tickets/new', to: 'tickets#new', as: 'new_team_ticket'
  post 'teams/:id/tickets', to: 'tickets#create', as: 'create_team_ticket'
    
  #For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  match "*path", to: "users#dashboard", via: :all
end

app/models/manager.rb
class Manager < ApplicationRecord
    has_and_belongs_to_many :teams
    attr_accessor :flag

    has_secure_password
    validates :first_name, presence: true, allow_blank: false
    validates :last_name, presence: true, allow_blank: false
    validates :watiam, format: {without: /[\s\W]/}, presence: true, allow_blank: false
    validates :password, length: {in: 6..25}, on: :create, format: {without: /\s/}, allow_blank: false, presence: true
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :require_login, except: [:new, :create]
  before_action :set_manager, only: [:show, :edit, :update, :destroy] # this was og the other two were randomly added to match user and havent been tested yet ¯\_(ツ)_/¯
  before_action :authorized_to_modify_and_destroy, only: [:edit, :update, :destroy]

  # GET /managers/new
  def new
    manager_params = params
    @manager = Manager.new
    if manager_params[:flag] == "Manager"
      @manager = Manager.create
    end
  end
    
  # GET /manager_dashboard
  def dashboard
    @manager = current_user_is_manager
    if !@manager
        redirect_to_manager_login
    else
      @CURRENT_SURVEY_DUE_DATE = CURRENT_SURVEY_DUE_DATE
    end 
  end
  
  # GET /team_health/1/metrics
  def team_health
    @CURRENT_SURVEY_DUE_DATE = CURRENT_SURVEY_DUE_DATE
    if !current_user_is_manager
      redirect_to_manager_login
    end
    @team = Team.find(params[:id])
    if !current_user_is_on_team(@team)
        redirect_to manager_dashboard_path, alert: 'You do not have permission to view this team.'
    else
      @team_health = true
      @team_users = @team.users
      @users = User.get_ordered_survey_indicator(@team, CURRENT_SURVEY_DUE_DATE) 
      @team_health_history = @team.get_health_history(CURRENT_SURVEY_DUE_DATE) 
        
      if @team_health_history.present?
        @health_value = @team_health_history[0][6] 
      else 
        @health_value = 0
      end
    end
  end

  # POST /managers
  def create    
    if manager_params[:flag] == "Manager"
      @manager = Manager.new(manager_params)
    else
      @manager = User.new(manager_params) 
    end
      
    @userCannotBeCreated = false
    @watiamList = User.select("watiam") + Manager.select("watiam")
    @watiamList.each do |x|
        if @manager.watiam == x.watiam
            @userCannotBeCreated = true
        end
    end
    if @userCannotBeCreated == false
        if @manager.save
          log_in @manager
          redirect_to root_url, notice: 'Account created and logged in.'
        else
          render :new
        end
    else
        flash[:alert] = "That WATIAM has an account associated with it already."
        render :new
    end
  end
    
  def tickets
    @team = Team.find(params[:id])
    if current_user_is_manager
      if current_user.teams.include?(@team)
        @tickets = @team.get_tickets(CURRENT_SURVEY_DUE_DATE)
      else 
        redirect_to manager_dashboard_path, alert: "You do not have permission to view these tickets." 
      end
    else
      redirect_to user_dashboard_path, alert: "You do not have permission to view tickets." 
    end
  end
    
  def health_details
    q1 = "How do you feel about this week in comparison to last week?"
    q2 = "How did you feel about this week?"
    q3 = "How would you rate your communication with your team members this week?"
    q4 = "How do you feel about the workload you had this week?"
    @questions = [q1,q2,q3,q4]

    due_date = Date.parse(params[:date])
    @interval = "#{due_date-7} - #{due_date-1}"
    if due_date == CURRENT_SURVEY_DUE_DATE
        @current_week = true
    else
        @current_week = false
    end

    @team = Team.find(params[:id])
    @surveys = []
    if current_user_is_manager
      if current_user.teams.include?(@team)
          @surveys = Survey.where(team_id: @team.id, date: params[:date])       
          @tickets = @team.get_tickets(due_date)
      else
        redirect_to manager_dashboard_path, alert: "You do not have permission to view this team's health."
      end
    else
      redirect_to_manager_login
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def manager_params
      params.require(:manager).permit(:name, :flag, :watiam, :password, :first_name, :last_name, :password_confirmation)
    end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_form.html.erb
<%= form_with(model: manager, local: true) do |form| %>
  <% if manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
        <% manager.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 
    
<div class="row-container">     
  <%= form.radio_button :flag, "User", :style => "display: none;" %>
  <%= form.label :flag_user, "User", :class => 'label' %> 
  <%= form.radio_button :flag, "Manager", :checked => true %>
  <%= form.label :flag_manager, "Manager", :class => 'label' %>   
</div> 
<!-- 
  - Source (https://stackoverflow.com/questions/50453091/override-a-default-value-in-a-rails-form) used for understanding how to set input values if default values not provided
-->

<div class="field">
    <%= form.text_field :watiam, value: (form.object.watiam || params[:watiam]), placeholder: "Watiam" %>
  </div>
<div class="field">
    <%= form.text_field :first_name, value: (form.object.first_name || params[:first_name]), placeholder: "First Name" %>
  </div>
<div class="field">
    <%= form.text_field :last_name, value: (form.object.last_name || params[:last_name]), placeholder: "Last Name" %>
  </div>

 <div class="field">
    <%= form.password_field :password, value: (form.object.password || params[:password]), placeholder: "Password" %>
  </div>

  <div class="field">
    <%= form.password_field :password_confirmation, value: (form.object.password_confirmation || params[:password_confirmation]), placeholder: "Password Confirmation" %>
  </div>

<div class="actions">
    <%= form.submit "Create Account", style: 'width: 180px' %>
  </div>
  
<% end %>

app/views/managers/dashboard.html.erb
<h1>Welcome <%= @manager.first_name.capitalize %>!</h1>
<h3>Weekly Survey Due Date: <%= @CURRENT_SURVEY_DUE_DATE-1 %> 11:59PM UTC</h3>
<br>
<table>
  <thead>
    <tr>
      <th>My Teams</th>
      <th>Current Weekly Health</th>
      <th>Weekly Survey Completion Ratio</th>
      <th>Tickets</th>
    </tr>
  </thead>
  <tbody>
    <% @manager.teams.each do |team| %>
      <tr>
        <td><%= link_to team.name, team_health_path(team) %>  </td>
        <% if team.get_total_team_health(0, @CURRENT_SURVEY_DUE_DATE).to_i <30 %>
            <td class = "red_notice"><%= team.get_total_team_health(0, @CURRENT_SURVEY_DUE_DATE) %> %</td>
        <% elsif team.get_total_team_health(0, @CURRENT_SURVEY_DUE_DATE).to_i >90 %>
            <td class = "green_notice"><%= team.get_total_team_health(0, @CURRENT_SURVEY_DUE_DATE) %> %</td>
        <% else %>
            <td><%= team.get_total_team_health(0, @CURRENT_SURVEY_DUE_DATE) %> %</td>
        <% end %>
        <% if team.any_completed_surveys(@CURRENT_SURVEY_DUE_DATE) %>
            <td><%= link_to "#{team.get_survey_completion_ratio(@CURRENT_SURVEY_DUE_DATE)} students have completed", team_health_details_path(id: team.id, date: @CURRENT_SURVEY_DUE_DATE, current_week: true) %></td>
        <% else %>
            <td><%= team.get_survey_completion_ratio(@CURRENT_SURVEY_DUE_DATE) %> students have completed</td>
        <% end %>
        <% if Ticket.where(team_id: team.id, date: @CURRENT_SURVEY_DUE_DATE-7...@CURRENT_SURVEY_DUE_DATE).length > 0 %> 
          <td><%= link_to 'View Tickets', team_tickets_path(team) %></td>
            <% else %>
          <td>No Tickets Yet</td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div class="link-container">
    <%= link_to 'New Team', new_team_path %>
</div>

<br><br>

<br><br>
<div class="link-container"> 
    <a href="#help"><h2>Confused?🤔 Get information here!</h2></a>
</div>

<div id="help" class="overlay">
  <div class="popup">
    <h3 style="text-align:left">Your Dashboard:</h3>
    <p style="margin-left:10px; margin-right:5%;">
        Welcome to your dashboard! Here you can view all of the teams you manage!
        <br>
        <br>
        The table displayed above shows you all of your teams, their weekly health, and the number of students in the team who have completed this week's survey. 
        You can click on the view tickets link for each team to see a list of tickets team members submitted for the current week.
        <br>
        To find out more about what weekly health means, click on any of your teams and using the 'Confused? Get information here!' link!
        You can also find out more about tickets by clicking the view tickets link. 
        <br><br>
        <b>What if I don't have any teams yet?😲</b>
        <br>
        No problem! You can easily create a new team and start monitoring that team's health by clicking the "New Team" link found under the My Teams table. 
        However, note that students must create an account first before you can add them to a team. Happy team building!
    </p>
    <h3 style="text-align:left">Weekly Survey Information:</h3>
    <p style="margin-left:10px; margin-right:5%;">
        The weekly survey information is where we display the questions that your amazing team members will be answering this week!🙌🙌🙌
        <br><br>
        <b>How does this work?</b>
        <br>
        Every week, your team members will be able to respond to the displayed questions.
        <br>
        Please note, that if there are any personal issues between members, either member can create a ticket. For more information on tickets, click the 'View All Tickets' link at the bottom of your dashboard and then use the 'Confused? Get information here!' link below!
        <br><br>
        <b>What do these ratings mean?</b>
        <br>
        Generally, we like to think of these ratings as follows:
        <br>
    </p>
    <p style="margin-left:30px">
        1: 😭 - Absolutely terrible
        <br>
        2: 😟 - It could be better
        <br>
        3: 😐 - Meh, could be better could be worse.
        <br>
        4: 🙂 - Hey, this is pretty good
        <br>
        5: 🥳 - Loved it; 10/10 would do that again
    </p>
    <br>
    <p style="margin-left:10px; margin-right:5%;">
        <b>What is the Weekly Survey Due Date?</b>
        <br>
        The weekly survey due date is, well, the deadline for your team members to submit the current week's survey.
        <br>
        Each week the team will be able to complete a new survey for that week. 
        <br>
        The due date is displayed in UTC to accomodate for the fact that team members may be in different timezones. 
        <br><br>
        <b>Cool! But what is the point of the surveys?</b>
        <br>
        We are so happy you asked!
        <br>
        We make sure to record all of the ratings your team members input every week. This data is then processed by a super secret algorithm our programming wizards created!🧙 After the algorithm has chewed on the ratings, it spits out a value representing your team's health!
        <br><br>
        <b>Yeah and?</b>
        <br>
        Now this is the cool part! Your team health is an overall reflection of your team members' feelings about work as well as any inter-personal team health issues. The best part? You get to see all of this in one website!
        <br><br>
    </p>
    <h3 style="text-align:left">What if I want more information about my team?</h3>
    <p style="margin-left:10px; margin-right:5%;">
        If you want to see more detailed information about a certain team's health or you want to edit a team simply click on that team's name and check out everything there is to know about your team!
    </p>
    <a href="#">Close</a>
  </div>
</div>

app/views/managers/health_details.html.erb
<% if params[:current_week]%>
    <h1><%= @team.name %> Surveys for Current Week</h1>
    <h3>Weekly Survey Due Date: <%= Date.parse(params[:date])-1 %> 11:59PM UTC</h3>
    <br>
<% else %>
    <h1><%= @team.name %> Health Details for Week <%= @interval %> </h1>
    <% if @current_week %>
        <h3>Weekly Survey Due Date: <%= Date.parse(params[:date])-1 %> 11:59PM UTC</h3>
    <% end %>
    <br>
    <h2>Survey Details</h2>
<% end %>
<% if @surveys.first && @surveys.first.responses.exists? %> 
    <table>
      <thead>
        <tr>
          <th>Questions Asked This Week</th>
        </tr>
      </thead>
      <tbody>
        <% for i in 0..@questions.length - 1 do  %>
          <tr>
            <td><%=i+1%> . <%= @questions[i]  %>  </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <br>
        <%= render template: 'surveys/list' %>
<% else %>
    <br>
    <div class="link-container"><strong>Your team did not submit any surveys this week! Please remind your team members to submit their surveys.</strong> </div>
    <br>
<% end %>
<br>

<% if params[:current_week]%>
    <div class="link-container">
        <%= link_to "Return to Dashboard", manager_dashboard_path %> 
    </div>
<% else %>
   <br>

    <h2>Ticket Details</h2>
        <% if @tickets.length > 0 %>
          <%= render template: 'tickets/list' %>
        <% else %>
            <br>
            <div class="link-container"><strong>Your team did not submit any tickets this week.</strong></div>
            <br>
        <% end %>  
    <br>
    <div class="link-container">
        <%= link_to "Back to #{@team.name}", team_health_path(@team)%>    
    </div>
<% end %>

<br><br>
<div class="link-container">
    <a href="#help"><h2>Confused?🤔 Get information here!</h2></a>
</div>

<div id="help" class="overlay">
  <div class="popup">
    <h3 style="text-align:left">Team surveys:</h3>
    <p style="margin-left:10px; margin-right:5%;">
        This is where you can find out more information about each week's survey!
        <br>
        <br>
        For each week you will be able to see all the questions that were asked in the survey.
        <br>
        Below that there is a table with each member and their respective ratings for each question during that week and their individual survey health.
        <br><br>
        <b>What about tickets?</b>
        <br>
        If any of your team members completed any tickets during the respective week, the ticket will also be displayed with all of their scores!
    </p>
    <a href="#">Close</a>
  </div>

app/views/managers/new.html.erb
<h1>Create Account</h1>

<%= render 'form', manager: @manager %>

<div class="link-container">  
<%= link_to "Already have an account? Sign in here!", login_path %>
</div>  

app/views/managers/team_health.html.erb
<h1><%=@team.name%> Health Metrics</h1>

<%= render template: 'teams/health' %>

<h2>Members</h2>
<% if @team.users.length != 0 %>
    <%= render template: 'teams/members' %>
<% else %>
    <div class="link-container">This team has no members. Let's start tracking this team's health by adding members. Edit Team below!</div>
<% end %>
<br>

<div class="link-container">
   <%= link_to 'Edit Team', edit_team_path(@team) %> 
</div>

<br><br>
<h2>Team Health History</h2>
<% if @team_health_history.length > 0 %>
    <table>
      <thead>
        <tr>
          <th>Week</th>
          <th>Communication</th>
          <th>Behaviour</th>
          <th>Teamwork</th>
          <th>Availability</th>
          <th>Weekly Surveys</th>
          <th>Team Health</th>
        </tr>
      </thead>
      <tbody>
        <% for i in 0..@team_health_history.length - 1 do %>
          <tr>
            <td><%= link_to @team_health_history[i][0], team_health_details_path(id: @team.id, date: @CURRENT_SURVEY_DUE_DATE - 7*i) %></td>
            <td><%= @team_health_history[i][1] %>%</td>
            <td><%= @team_health_history[i][2] %>%</td>
            <td><%= @team_health_history[i][3] %>%</td>
            <td><%= @team_health_history[i][4] %>%</td>
            <td><%= @team_health_history[i][5] %>%</td>
                <% if @team_health_history[i][6].to_i < 30 %>
                    <td class="red"><b><%= @team_health_history[i][6] %>%</b></td>
                <% elsif @team_health_history[i][6].to_i > 90 %>
                    <td class="green"><b><%= @team_health_history[i][6] %>%</b></td>
                <% else %>
                    <td><b><%= @team_health_history[i][6] %>%</b></td>
                <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
<% else %>
    <div class="link-container">No historical data available.</div>
<% end %>

<br><br>
<div class="link-container">
    <%= link_to 'Return to Dashboard', manager_dashboard_path %>
</div>

<br><br>
<div class="link-container">
    <a href="#help"><h2>Confused?🤔 Get information here!</h2></a>
</div>

<div id="help" class="overlay">
  <div class="popup">
    <h3 style="text-align:left">Team Health:</h3>
    <p style="margin-left:10px; margin-right:5%;">
        This is the place to be if you want to know more about your team's health!
        <br>
        <br>
        <b>Current Week's Team Health</b>
        <br>
        At the top of the page you will find a quick visualization that reflects your current week's team health.
        <br><br>
        The weekly team health is a direct reflection of how your team feels about the current week as well as how they feel about their teammates!
        <br>
        It's simple! The higher the number, the happier your team is!🥳
        <br><br>
        <b>How will I know if my team members actually are completing their weekly surveys?</b>
        <br>
        We are glad you asked! Below the team health visualization we have a quick table that displays:
    </p>
    <p style="margin-left:30px">
        - Team Member WatIAm
        <br>
        - First Name
        <br>
        - Last Name
        <br>
        - Weekly survey completion status
    </p>
    <p style="margin-left:10px; margin-right:5%;">
        <br>
        That last column is the most imporant one! Every week you will be able to see whether or not every team member has completed their survey.
        <br>
        Here at Paen, we recommend that you do your best to motivate your team members to always complete their surveys, as the more team members complete their surveys, the more accurate our estimation will be!
    </p>
    <p style="margin-left:10px; margin-right:5%;">
        <br>
        <b>What are the zeros in the team health table?</b>
        <br>
        If you see zeroes under communication, behaviour, teamwork, or availability, that means the team members did not submit any tickets for that week.
        Similarly, zeroes under weekly survey means none of the team members completed their survey that week.
        The team health is calculated with a combination of tickets and weekly surveys, so it will be nonzero as long as one of the two has been submitted.
    </p>
    <h3 style="text-align:left">What if my team roster needs some touch-ups?</h3>
    <p style="margin-left:10px; margin-right:5%;">
        Teamwork makes the dream work, right?🧐
        <br>
        If your team list needs to be updated, use the "Edit Team" link under the Members table.
    </p>
    <h3 style="text-align:left">What is Team Health History?</h3>
    <p style="margin-left:10px; margin-right:5%;">
        You know how we have that super cool team health visualization for this week's health at the top of the page?
        <br>
        What if we told you, that you could see the history of your team's health??😮 Don't believe me?
        <br><br>
        Great news: you can click on any of the past weeks to view details on the team health of that week!
        <br><br>
    </p>
    <a href="#">Close</a>
  </div>
</div>

app/views/managers/tickets.html.erb
<h1><%= @team.name %> Tickets for Current Week</h1>

<% if @tickets.length > 0 %>
<%= render template: 'tickets/list' %>
<% else %>
<div class="link-container"><strong>Your team did not submit any tickets this week.</strong></div>
<% end %>
<br>
<div class="link-container"><%= link_to 'Return to Dashboard', manager_dashboard_path %></div>

<br><br>
<div class="link-container"><a href="#help"><h2>Confused?🤔 Get information here!</h2></a></div>

<div id="help" class="overlay">
  <div class="popup">
    <h3 style="text-align:left">My Team's Tickets:</h3>
    <p style="margin-left:10px; margin-right:5%;">
        This is the place to be if you want to know how your team feels about one another!
        <br><br>
        <b>Isn't that what the team health is for?</b>
        <br>
        Yes and no. The team health (displayed in your team view) shows you an overview of all of your team member's combined reflections and ratings of the previous week (and optionally, each other).
        <br><br>
        But what if your team member had more specific issues with another team member?
        <br>
        That is exaclty what a ticket is made for!😁
        <br><br>
        <b>So how do these tickets work?</b>
        <br>
        Every week, in addition to the survey, a team member may choose to create a ticket reflecting their personal concerns or feelings about other team members.
        <br><br>
        Within the ticket we allow the team member to select one of the members of that team and complete a form with the following prompts:
    </p>
    <p style="margin-left:30px">
        1. I've experience _____ communication with this person
        <br>
        2. I've experienced _____ behaviour with this person
        <br>
        3. I've experienced _____ teamwork with this person
        <br>
        4. I've experienced _____ availability with this person
        <br>
        Overall rating: _____
    </p>
    <p style="margin-left:10px; margin-right:5%;">
        For the numbered questions, the ticket creator will be able to choose one of the following options to complete the prompt the way they deem best:
    </p>
    <p style="margin-left:30px">
        1. great
        <br>
        2. typical
        <br>
        3. poor
    </p>
    <p style="margin-left:10px; margin-right:5%;">
        In addition to the numbered questions, the team member creating the ticket will also be able to submit an overall rating.
        <br><br>
        <b>So what? They can provide feedback. How does this affect me?</b>
        <br>
        Aside from being able to view direct feedback between team members, these ticket scores are factored into the team's weekly team health.
        <br><br>
        <b>Anything else I need to know?</b>
        <br>
        Oh yeah, one more thing. These tickets are completely optional for team members. We like to think of them as something that your team members should complete if the team health issue at hand needs to be highlighted to the team manager.
    </p>
    <a href="#">Close</a>
  </div>
</div>