config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  resources :surveys, except: [:index, :show, :edit, :new, :update, :destroy]
  resources :managers, except: [:index, :show, :edit, :update, :destroy]
  resources :teams, except: [:index, :show]
  resources :responses, except: [:index, :show, :edit, :new, :update, :destroy]
  resources :ticket_responses, except: [:index, :show, :edit, :new, :update, :destroy]
  resources :users, except: [:new, :index, :show, :edit, :update, :destroy]  
  resources :tickets, except: [:new, :show, :index, :edit, :update, :destroy]
    
  get '/signup', to: 'users#new'
  get '/login',  to: 'sessions#new'    
  post '/login',  to: 'sessions#create'    
  get '/logout', to: 'sessions#destroy' 
  
  get '/about', to: 'static_pages#about'
    
  get 'dashboard', to: 'users#dashboard', as: 'user_dashboard'
  get 'dashboard/teams/:id', to: 'users#team_list', as: 'user_team_list'    
  get 'dashboard/teams/:id/weekly_surveys/:from', to: 'users#weekly_surveys', as: 'weekly_surveys'
    
  get 'manager_dashboard', to: 'managers#dashboard', as: 'manager_dashboard'
  get 'team_health/:id/metrics', to: 'managers#team_health', as: 'team_health'
    
  get 'teams/:id/members', to: 'teams#edit_members', as: 'edit_members'
  post 'teams/:id/members/add', to: 'teams#add_member', as: 'confirm_add_member'
  post 'teams/:id/members/remove', to: 'teams#remove_member', as: 'confirm_remove_member'
  
  get 'teams/:id/tickets', to: 'managers#tickets', as: 'team_tickets'
  get 'team_health/:id/metrics/:date/details', to: 'managers#health_details', as: 'team_health_details'
    
    # route to get the team associated with the ticket
  get 'teams/:id/tickets/new', to: 'tickets#new', as: 'new_team_ticket'
  post 'teams/:id/tickets', to: 'tickets#create', as: 'create_team_ticket'
    
  #For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  match "*path", to: "users#dashboard", via: :all
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>W2021Team2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;600;700;800;900&display=swap" rel="stylesheet">
  </head>

  <body>
    <!-- source: https://stackoverflow.com/questions/1203892/how-can-i-find-out-the-current-route-in-rails -->
    <% @current_route = request.env['PATH_INFO'] %>
    <% if @current_route != "/login" && @current_route != "/signup" && @current_route != "/users" && @current_route != "/managers" %>
        <div class="header-container">        
            <a id="logo" href="<%= current_user_is_manager ? "/managers_dashboard" : "/dashboard" %>"> <%= image_tag("logo.png", class: "logo") %> </a>
            <div class="row-container", style="align-self:center;">
                <%= button_to 'About', about_path, :method =>"get", :class => "about_button" %> 
                &nbsp;
                <%= button_to 'Logout', logout_path, :method =>"get", :class => "logout_button" %> 
            </div>
        </div>
     <% else %>
         <div class="row-container">        
            <%= image_tag("logo.png", class: "logo", style: "align-self: center;") %>
        </div>
        <br>
     <% end %>
      
    <% flash.each do |key, value| %>
        <%= content_tag :div, value, id: "#{key}" %>    
    <% end %>  
      
    <%= yield %>
  </body>
</html>